# -*- coding: utf-8 -*-
"""CodeAlpha_Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z05IuLvYr57O66yZkPfEZeMrtVPmesv5

**IMPORT LIBRARIES**
"""

!pip install nltk
!pip install wordcloud

import pandas as pd
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
import matplotlib.pyplot as plt
from wordcloud import WordCloud

nltk.download('vader_lexicon')

"""UPLOAD DATASET"""

from google.colab import files
uploaded = files.upload()

"""LOAD DATASET"""

df = pd.read_csv("netflix_titles.csv")

df['description']

"""SENTIMENT SCORES"""

sia = SentimentIntensityAnalyzer()

def get_sentiment(text):
    score = sia.polarity_scores(str(text))['compound']

    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

df['sentiment'] = df['description'].apply(get_sentiment)

df[['description','sentiment']].head()

"""SENTIMENT DISTRIBUTION"""

df['sentiment'].value_counts()

plt.figure(figsize=(6,4))
df['sentiment'].value_counts().plot(kind='bar')
plt.title("Sentiment Distribution of Netflix Content Descriptions")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.show()

"""SENTIMENT PERCENTAGE"""

sentiment_percent = df['sentiment'].value_counts(normalize=True) * 100
print(sentiment_percent)

"""WORD CLOUD (POSITIVE DESCRIPTIONS)"""

positive_text = " ".join(df[df['sentiment']=="Positive"]['description'])

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(positive_text)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Positive Sentiment Word Cloud")
plt.show()

"""WORD CLOUD (NEGATIVE DESCRIPTIONS)"""

negative_text = " ".join(df[df['sentiment']=="Negative"]['description'])

wordcloud = WordCloud(width=800, height=400, background_color='black').generate(negative_text)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Negative Sentiment Word Cloud")
plt.show()