# -*- coding: utf-8 -*-
"""CodeAlpha_Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TabA-21OQeB4VKiYA7GTSplIE3ZXD52L

IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

"""UPLOAD DATASET"""

from google.colab import files
uploaded = files.upload()

"""LOAD DATASET"""

df = pd.read_csv("netflix_titles.csv")

"""MOVIES VS TV SHOWS"""

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='type')
plt.title("Distribution of Movies vs TV Shows")
plt.xlabel("Content Type")
plt.ylabel("Count")
plt.show()

"""CONTENT RELEASE TREND"""

content_year = df['release_year'].value_counts().sort_index()

plt.figure(figsize=(12,6))
content_year.plot()
plt.title("Content Release Trend Over Years")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")
plt.show()

"""TOP 10 COUNTRIES"""

top_countries = df['country'].value_counts().head(10)

plt.figure(figsize=(10,5))
sns.barplot(x=top_countries.values, y=top_countries.index)
plt.title("Top 10 Content Producing Countries")
plt.xlabel("Number of Titles")
plt.ylabel("Country")
plt.show()

"""RATINGS DISTRIBUTION"""

plt.figure(figsize=(10,6))
sns.countplot(data=df, y='rating', order=df['rating'].value_counts().index)
plt.title("Content Ratings Distribution")
plt.xlabel("Count")
plt.ylabel("Rating")
plt.show()

"""MOVIE DURATION ANALYSIS"""

movies = df[df['type'] == 'Movie'].copy()

movies['duration'] = movies['duration'].str.replace(" min","")
movies['duration'] = movies['duration'].astype(float)

plt.figure(figsize=(10,5))
sns.histplot(movies['duration'], bins=30)
plt.title("Movie Duration Distribution")
plt.xlabel("Duration (Minutes)")
plt.ylabel("Frequency")
plt.show()

"""DATA CLEANING"""

df['date_added'] = pd.to_datetime(df['date_added'], format='mixed')
df['year_added'] = df['date_added'].dt.year
df['country'] = df['country'].fillna("Unknown")

"""CONTENT ADDED OVER TIME"""

added_year = df['year_added'].value_counts().sort_index()

plt.figure(figsize=(12,6))
added_year.plot()
plt.title("Content Added to Netflix Over Time")
plt.xlabel("Year Added")
plt.ylabel("Number of Titles")
plt.show()

"""CORRELATION HEATMAP"""

numeric_df = df.select_dtypes(include=['int64','float64'])

plt.figure(figsize=(6,4))
sns.heatmap(numeric_df.corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()