# -*- coding: utf-8 -*-
"""CodeAlpha_Exploratory Data Analysis (EDA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K94V31FPNjlPvHOJx99T8ktvlkGEXyrR

IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

"""UPLOAD DATASET"""

from google.colab import files
uploaded = files.upload()

"""LOAD DATASET"""

df = pd.read_csv("netflix_titles.csv")

print("Dataset Shape:", df.shape)
df.head()

"""DATA STRUCTURE"""

print("\nDataset Info:\n")
df.info()

print("\nStatistical Summary:\n")
df.describe()

"""MISSING VALUES"""

missing_values = df.isnull().sum()
print("\nMissing Values:\n", missing_values)

plt.figure(figsize=(10,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap")
plt.show()